### ISSUE TITLE
Basic HIV model

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel-Gallery#3]

**Comment by connor-vanmeter** [comment]
- [ ] Set up tracking on HIV status and ART status
- [ ] Write progression from Sus -> Acute (I) -> Chronic 1 (I) -> Chronic 2 (I) -> Final (I) -> Depart
- [ ] Write progression within each (I) compartment for ART use -> no ART use AND no ART use -> ART use
- [ ] Establish starting counts at start of model for HIV status and ART status
- [ ] Code different transmission probabilities for HIV status and ART status

**Comment by connor-vanmeter** [comment]
## Updates 
- [ ] Check ART Treatment, Discontinuance, and Progression Reduction Rates
- [ ] Update PPT model description to only include slide 4.
- [ ] Remove flow from AIDS to general departure flow
- [ ] PPT to PNG image and embed in README. Remove PPT.
- [ ] Remove mentions of departure.disease.mult from model and module
- [ ] Instead of net flow between ART compartments, track people flowing from ART to no ART and vice versa. No negative numbers!
- [ ] Instead of multiple HIV stage time attributes, only have one stage time attribute that resets to 0 when an individual transitions between stages
- [ ] Instead of multiple ART time attributes, only have one ART time attribute that resets to 0 when an individual transitions between ART status
- [ ] Instead of including !is.na(attribute), include ", na.rm = TRUE" at end of line
- [ ] Remove aggregate counts and keep stratified only, matching the updated model diagram in README
- [ ] Where instances of initialized zero counts, remove and update references to length(vector) > 0
- [ ] Include summary statistics at the end of each module rather than embedded in module

**Comment by connor-vanmeter** [comment]
Hi @smjenness. I have completed the update and retest actions for the HIV model noted in the above comment. I have not yet started my practicum due to processing delays and, pending my start remains delayed, can stop by the office sometime this week to review the changes if you prefer to review in-person and if you have the time. Thanks!
